<?php
if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
     $matric = $_POST['matric'];

     // It is assumed that you have coonnected to your db and extracted the full details of the students to be displayed in the document.

     $FullName = 'NYAAKU OLUWAYEMISI ESTHER'; // Assumed Full Name from Database
     $course =     'Computer Science'; // Assumed Course from database

     $date = date("d-F-Y"); // This can be autogenerated or generated from your datbase, depending on purpose. 

     ob_start();

        require('pdfClass.php'); // The main content is defined this file
        
                        $pdf=new document('P', 'mm', 'A4');
                        // The document is Portait and A4
					
					   
						$pdf->SetAutoPageBreak(true,10);
                        $pdf->AddPage();
                        
                        $logo = file_get_contents('images/lasu.jpg');
                        // Change the image to original image

                        
                        $signature = file_get_contents('signature/signature.jpg');
                        // Use quality scanned signature


                       
                        // The draft function is called in fdf; for more details about what this draft function does,
                        // check the function draft in the "pdfclass.php" file @ line 218
					  
                        $pdf->draft($matric, $FullName, $course, $date);
                        
                        // Typically, all the variables to be used in included in this function which should be defined in the pdf class

                         
                        // dimesnions are : x-axis (horizontal), y-axis (vertical), width , height
						
					
						//$pdf-> imageLoader();                    
                        $pdf->MemImage($logo, 90, 5, 25,25); // Logo

                        $pdf->MemImage($signature, 20, 110, 25,25); // Signature
                        // Adjust the position as you deem fit
                        
        
       // $pdf->Output('downloads/' . $matric.".pdf",'F'); // This downloads on the server.

         //$pdf->Output($matric.".pdf",'I'); // This opens in a new browser

              $pdf->Output($matric.".pdf",'D'); // This downloads on the client machine, using clients matric or ID
    	ob_end_flush();

    
}

?>

<!DOCTYPE HTML>
<html>
<head>

<title>LASU | Admission Screening</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />

<link href="css/bootstrap.css" rel='stylesheet' type='text/css' />

<!-- Custom CSS -->
<link href="css/style.css" rel='stylesheet' type='text/css' />

<!-- font-awesome icons CSS -->
<link href="css/font-awesome.css" rel="stylesheet"> 
<!-- //font-awesome icons CSS -->

<body>
        <div style = "width:20%;margin-left:30px">
            <form method = "POST" action = "<?php echo htmlspecialchars($_SERVER['PHP_SELF']); ?>">
                        <div class="form-group"> 
                                        <label for="exampleInputEmail1"><strong>Matriculation Number</strong></label>
                                        <input type="text" class="form-control" name = "matric"  required>
                                        <p class="help-block" style = "color:red"> </p> 
                        </div>

                        <div class="form-group"> 
                                       <button type = "submit" class = "btn btn-primary"> Print </button>
                        </div>
            </form>
        </div>

</body>
 


 </html>
 
